FPS = 60
ASSETS_DIR = "assets"
CHARACTERS_DIR = f"{ASSETS_DIR}/characters/"
CHARACTERS_SPRITS_FOLDER = "Sprites"
BACKGROUNDS_DIR = f"{ASSETS_DIR}/backgrounds/"
BLACK = (0, 0, 0)
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 700